name: grpc_service_chat
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  rxdart: ^0.27.0

  #grpc
  grpc: ^3.0.0
  protobuf: ^2.0.0
  protoc_plugin: ^20.0.0  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
